version: "3.8"

services:

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        user: luka
        uid: 1000
    image: cloudsigma.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    command: php artisan serve
    ports:
      - "9000:9000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./backend:/var/www/html/
      - ./backend/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    depends_on:
      - db
    networks:
      - app-network

  nextjs:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    image: cloudsigma.com/nextjs
    container_name: nextjs
    restart: unless-stopped
    tty: true
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      SERVICE_NAME: nextjs
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./frontend:/var/www/html/
    depends_on:
      - app
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - nextjs
    networks:
      - app-network

  db:
    image: mariadb:10.6
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local